server:
  port: 8282
  servlet:
    context-path: /

cloud:
  aws:
    credentials:
      accessKey:
      secretKey:
      instanceProfile: false
      useDefaultAwsCredentialsChain: true
    region:
      static: ap-south-1
    stack:
      auto: false

queue:
  order: order-queue
  payment: payment-queue
  restaurant: restaurant-queue